/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GymSystem;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhishek Mane
 */
public class AddRecords extends javax.swing.JFrame {

    /**
     * Creates new form AddRecords
     */
    Dashboard dab;
    
    public AddRecords() {
        super("Add Records");
        initComponents();
        fetchUserIdComboBox(userCombo);
        fetchInstructorComboBox(instCombo);
        fetchPaymentComboBox(pidCombo);
        fetchMemShipComboBox(msCombo);
        fetchFloorComboBox(floorCombo);
    }
    
    public AddRecords(Dashboard d) {
        super("Add Records");
        initComponents();
        dab = d;
        
        fetchUserIdComboBox(userCombo);
        fetchInstructorComboBox(instCombo);
        fetchPaymentComboBox(pidCombo);
        fetchMemShipComboBox(msCombo);
        fetchFloorComboBox(floorCombo);
    }
    
    public void fetchFloorComboBox(JComboBox jb){
        try {
            Database db = new Database();
            String query = "select * from floor";
            ResultSet rs = db.stmt.executeQuery(query);
            
            while (rs.next()) {
               jb.addItem(rs.getString("floor_id"));
            }
            
        } catch (Exception e) {
        }
    }
    
     public void fetchPaymentComboBox(JComboBox jb){
        try {
            Database db = new Database();
            String query = "select * from payment";
            ResultSet rs = db.stmt.executeQuery(query);
            
            while (rs.next()) {
               jb.addItem(rs.getString("payment_id"));
            }
            
        } catch (Exception e) {
        }
    }
     
      public void fetchUserIdComboBox(JComboBox jb){
        try {
            Database db = new Database();
            String query = "select * from gymuser";
            ResultSet rs = db.stmt.executeQuery(query);
            
            while (rs.next()) {
               jb.addItem(rs.getString("user_id"));
            }
            
        } catch (Exception e) {
        }
    }
      
       public void fetchMemShipComboBox(JComboBox jb){
        try {
            Database db = new Database();
            String query = "select * from membership";
            ResultSet rs = db.stmt.executeQuery(query);
            
            while (rs.next()) {
               jb.addItem(rs.getString("membership_id"));
            }
            
        } catch (Exception e) {
        }
    }
      
        public void fetchInstructorComboBox(JComboBox jb){
        try {
            Database db = new Database();
            String query = "select * from instructor";
            ResultSet rs = db.stmt.executeQuery(query);
            
            while (rs.next()) {
               jb.addItem(rs.getString("instructor_id"));
            }
            
        } catch (Exception e) {
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gymmanagementsystemPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("gymmanagementsystemPU").createEntityManager();
        floorQuery = java.beans.Beans.isDesignTime() ? null : gymmanagementsystemPUEntityManager.createQuery("SELECT f FROM Floor f");
        floorList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : floorQuery.getResultList();
        floorQuery1 = java.beans.Beans.isDesignTime() ? null : gymmanagementsystemPUEntityManager.createQuery("SELECT f FROM Floor f");
        floorList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : floorQuery1.getResultList();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        emailfiled = new javax.swing.JTextField();
        namefield = new javax.swing.JTextField();
        midfiled = new javax.swing.JTextField();
        msCombo = new javax.swing.JComboBox<>();
        pidCombo = new javax.swing.JComboBox<>();
        userCombo = new javax.swing.JComboBox<>();
        instCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pomField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        msIdField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        toiMsField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        floorCombo = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        instEmailField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        instNameField = new javax.swing.JTextField();
        instIdField = new javax.swing.JTextField();
        instContactField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        floorNameField = new javax.swing.JTextField();
        floorIdField = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        paymentIdField = new javax.swing.JTextField();
        dateofpaymentField = new javax.swing.JTextField();
        amountField = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        itemIdField = new javax.swing.JTextField();
        itemQuantityField = new javax.swing.JTextField();
        itemNameField = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 200));
        setMinimumSize(new java.awt.Dimension(1230, 620));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add Records");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(550, 10, 230, 40);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 60, 1220, 20);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPanel1.setLayout(null);

        emailfiled.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        emailfiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfiledActionPerformed(evt);
            }
        });
        jPanel1.add(emailfiled);
        emailfiled.setBounds(170, 120, 220, 40);

        namefield.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(namefield);
        namefield.setBounds(600, 40, 220, 40);

        midfiled.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        midfiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midfiledActionPerformed(evt);
            }
        });
        jPanel1.add(midfiled);
        midfiled.setBounds(170, 40, 220, 40);

        msCombo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(msCombo);
        msCombo.setBounds(170, 290, 220, 40);

        pidCombo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(pidCombo);
        pidCombo.setBounds(170, 200, 220, 40);

        userCombo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(userCombo);
        userCombo.setBounds(600, 120, 220, 40);

        instCombo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(instCombo);
        instCombo.setBounds(600, 200, 220, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Membership ID -");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 290, 160, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Member ID -");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 40, 140, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Email -");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 120, 140, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Name -");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(440, 40, 140, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("User ID -");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(440, 120, 140, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Payment ID -");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 200, 140, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Instructor ID -");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(440, 200, 140, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setText("Add Member");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(840, -5, 370, 460);

        jTabbedPane1.addTab("Members", jPanel1);

        jPanel2.setLayout(null);

        pomField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(pomField);
        pomField.setBounds(220, 180, 260, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Membership ID -");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 30, 160, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Floor ID -");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 260, 90, 40);

        msIdField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        msIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msIdFieldActionPerformed(evt);
            }
        });
        jPanel2.add(msIdField);
        msIdField.setBounds(220, 30, 260, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Type of Membership -");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 100, 200, 40);

        toiMsField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(toiMsField);
        toiMsField.setBounds(220, 100, 260, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Price of Membership -");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 180, 200, 40);

        floorCombo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(floorCombo);
        floorCombo.setBounds(220, 260, 260, 40);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setText("Add Membership");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(749, 0, 460, 450);

        jTabbedPane1.addTab("Membership", jPanel2);

        jPanel3.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Email  -");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(20, 230, 180, 22);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Instructor ID -");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(20, 26, 140, 22);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Instructor Name  -");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(20, 90, 180, 22);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Contact  -");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(20, 160, 180, 22);

        instEmailField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instEmailFieldActionPerformed(evt);
            }
        });
        jPanel3.add(instEmailField);
        instEmailField.setBounds(220, 220, 240, 40);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Email  -");
        jPanel3.add(jLabel17);
        jLabel17.setBounds(20, 230, 180, 22);

        instNameField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(instNameField);
        instNameField.setBounds(220, 80, 240, 40);

        instIdField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instIdFieldActionPerformed(evt);
            }
        });
        jPanel3.add(instIdField);
        instIdField.setBounds(220, 20, 240, 40);

        instContactField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        instContactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instContactFieldActionPerformed(evt);
            }
        });
        jPanel3.add(instContactField);
        instContactField.setBounds(220, 150, 240, 40);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton3.setText("Add Instructor");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(880, 0, 330, 450);

        jTabbedPane1.addTab("Instructors", jPanel3);

        jPanel4.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Floor Name -");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(20, 90, 120, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("Floor ID -");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(20, 30, 90, 30);

        floorNameField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(floorNameField);
        floorNameField.setBounds(180, 80, 220, 40);

        floorIdField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        floorIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floorIdFieldActionPerformed(evt);
            }
        });
        jPanel4.add(floorIdField);
        floorIdField.setBounds(180, 20, 220, 40);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton4.setText("Add Floor");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(970, 0, 240, 450);

        jTabbedPane1.addTab("Floors", jPanel4);

        jPanel5.setLayout(null);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Date of Payment -");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(30, 170, 170, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Payment ID -");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(30, 30, 130, 30);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Amount -");
        jPanel5.add(jLabel22);
        jLabel22.setBounds(30, 100, 130, 30);

        paymentIdField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel5.add(paymentIdField);
        paymentIdField.setBounds(220, 30, 240, 40);

        dateofpaymentField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dateofpaymentField.setToolTipText("DD-MONTH-YY   Eg - 01-Jan-21");
        jPanel5.add(dateofpaymentField);
        dateofpaymentField.setBounds(220, 170, 240, 40);

        amountField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        amountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFieldActionPerformed(evt);
            }
        });
        jPanel5.add(amountField);
        amountField.setBounds(220, 100, 240, 40);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton5.setText("Add Payment");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5);
        jButton5.setBounds(910, 0, 300, 450);

        jTabbedPane1.addTab("Payment", jPanel5);

        jPanel6.setLayout(null);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Item Quantity -");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(30, 170, 150, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setText("Item ID -");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(30, 50, 90, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Item Name -");
        jPanel6.add(jLabel25);
        jLabel25.setBounds(30, 110, 120, 30);

        itemIdField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel6.add(itemIdField);
        itemIdField.setBounds(200, 40, 210, 40);

        itemQuantityField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel6.add(itemQuantityField);
        itemQuantityField.setBounds(200, 160, 210, 40);

        itemNameField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel6.add(itemNameField);
        itemNameField.setBounds(200, 100, 210, 40);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton6.setText("Add Inventory");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton6);
        jButton6.setBounds(910, 0, 300, 450);

        jTabbedPane1.addTab("Inventory", jPanel6);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 90, 1210, 480);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setText("Refresh");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(1080, 0, 130, 40);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(0, 0, 130, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailfiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailfiledActionPerformed

    private void midfiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midfiledActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midfiledActionPerformed

    private void msIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msIdFieldActionPerformed

    private void instIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instIdFieldActionPerformed

    private void instEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instEmailFieldActionPerformed

    private void instContactFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instContactFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instContactFieldActionPerformed

    private void floorIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floorIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floorIdFieldActionPerformed

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFieldActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:refresh
        this.setVisible(false);
         new AddRecords(dab).setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(midfiled.getText().isEmpty() || emailfiled.getText().isEmpty() || namefield.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "All Fields are Mandatory");
        }else if( !emailfiled.getText().contains("@")){
            JOptionPane.showMessageDialog(this, "Invalid Email ID");
            System.out.println("Invalid E - Mail");
        }else{
            try{
                Database db = new Database();
                String sql = "insert into member values(?,?,?,?,?,?,?)";
                PreparedStatement pst =  db.con.prepareStatement(sql);

                pst.setString(1, midfiled.getText());
                pst.setString(2, namefield.getText());
                pst.setString(3, emailfiled.getText());
                pst.setString(4, (String) userCombo.getSelectedItem());
                pst.setString(5, (String) pidCombo.getSelectedItem());
                pst.setString(6, (String) instCombo.getSelectedItem());
                pst.setString(7, (String) msCombo.getSelectedItem());

                pst.executeUpdate();

                JOptionPane.showMessageDialog(this,"1 Row Affected \n Record Added Successfully");
            }catch(Exception e){ JOptionPane.showMessageDialog(this, e); }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: insert in database
        if(msIdField.getText().isEmpty() || toiMsField.getText().isEmpty() || pomField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "All Fields Are Mandatory");
        }else if(Integer.parseInt(pomField.getText()) == (int)0 || Integer.parseInt(pomField.getText()) > (int)100000){
            JOptionPane.showMessageDialog(this, "Price Must be Greater than Zero \n&\n Price Must be less than One Lakh");
        }else{
            
            try{
                Database db = new Database();
                String sql = "insert into membership values(?,?,?,?)";
                PreparedStatement pst =  db.con.prepareStatement(sql);

                pst.setString(1, msIdField.getText());
                pst.setString(2, toiMsField.getText());
                pst.setInt(3, Integer.parseInt(pomField.getText()));
                pst.setString(4, (String) floorCombo.getSelectedItem());

                pst.executeUpdate();

                JOptionPane.showMessageDialog(this,"1 Row Affected \n Record Added Successfully");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
     }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if(instIdField.getText().isEmpty() || instNameField.getText().isEmpty() || instContactField.getText().isEmpty() || instEmailField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "All Fields Are Mandatory"); 
        }else if(!instEmailField.getText().contains("@") && instContactField.getText().length() != (int)10){
            JOptionPane.showMessageDialog(this, "Invalid Email \nOR\n Invalid Contact Number");
        }else{
        try{
                Database db = new Database();
                String sql = "insert into instructor values(?,?,?,?)";
                PreparedStatement pst =  db.con.prepareStatement(sql);

                pst.setString(1, instIdField.getText());
                pst.setString(2, instNameField.getText());
                pst.setString(3, instContactField.getText());
                pst.setString(4, instEmailField.getText());

                pst.executeUpdate();

                JOptionPane.showMessageDialog(this,"1 Row Affected \n Record Added Successfully");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         // TODO add your handling code here: floor
         if(floorIdField.getText().isEmpty() || floorNameField.getText().isEmpty()){
              JOptionPane.showMessageDialog(this, "All Fields Are Mandatory"); 
         }else if(floorIdField.getText() == null){
            JOptionPane.showMessageDialog(this,"Floor ID Can't be Empty ");
        }else{
        try{
                Database db = new Database();
                String sql = "insert into floor values(?,?)";
                PreparedStatement pst =  db.con.prepareStatement(sql);

                pst.setString(1, floorIdField.getText());
                pst.setString(2, floorNameField.getText());

                pst.executeUpdate();

                JOptionPane.showMessageDialog(this,"1 Row Affected \n Record Added Successfully");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here: payment
        if(paymentIdField.getText().isEmpty() || amountField.getText().isEmpty() || dateofpaymentField.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "All Fields Are Mandatory"); 
        }else if(Integer.parseInt(amountField.getText()) <= (int)0 && Integer.parseInt(amountField.getText()) <= (int)100000){
            JOptionPane.showMessageDialog(this,"Amount Must be greater than Zero \n & \n Amount Must be less than One Lakh");
        }else{
             try{
                Database db = new Database();
                String sql = "insert into payment values(?,?,?)";
                PreparedStatement pst =  db.con.prepareStatement(sql);

                pst.setString(1, paymentIdField.getText());
                pst.setInt(2, Integer.parseInt(amountField.getText()));
                pst.setString(3, dateofpaymentField.getText());

                pst.executeUpdate();

                JOptionPane.showMessageDialog(this,"1 Row Affected \n Record Added Successfully");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here: Inventory
        if(itemIdField.getText().isEmpty() || itemNameField.getText().isEmpty() || itemQuantityField.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "All Fields Are Mandatory"); 
        }else if(Integer.parseInt(itemQuantityField.getText()) <= (int)0 ){
            JOptionPane.showMessageDialog(this,"Item Quantity Must be greater than Zero");
        }else{
             try{
                Database db = new Database();
                String sql = "insert into inventory values(?,?,?)";
                PreparedStatement pst =  db.con.prepareStatement(sql);

                pst.setString(1, itemIdField.getText());
                pst.setString(2, itemNameField.getText());
                pst.setInt(3, Integer.parseInt(itemQuantityField.getText()));
                
                pst.executeUpdate();

                JOptionPane.showMessageDialog(this,"1 Row Affected \n Record Added Successfully");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here: refresh
         this.setVisible(false);
        dab.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JTextField dateofpaymentField;
    private javax.swing.JTextField emailfiled;
    private javax.swing.JComboBox<String> floorCombo;
    private javax.swing.JTextField floorIdField;
    private java.util.List<GymSystem.Floor> floorList;
    private java.util.List<GymSystem.Floor> floorList1;
    private javax.swing.JTextField floorNameField;
    private javax.persistence.Query floorQuery;
    private javax.persistence.Query floorQuery1;
    private javax.persistence.EntityManager gymmanagementsystemPUEntityManager;
    private javax.swing.JComboBox<String> instCombo;
    private javax.swing.JTextField instContactField;
    private javax.swing.JTextField instEmailField;
    private javax.swing.JTextField instIdField;
    private javax.swing.JTextField instNameField;
    private javax.swing.JTextField itemIdField;
    private javax.swing.JTextField itemNameField;
    private javax.swing.JTextField itemQuantityField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField midfiled;
    private javax.swing.JComboBox<String> msCombo;
    private javax.swing.JTextField msIdField;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField paymentIdField;
    private javax.swing.JComboBox<String> pidCombo;
    private javax.swing.JTextField pomField;
    private javax.swing.JTextField toiMsField;
    private javax.swing.JComboBox<String> userCombo;
    // End of variables declaration//GEN-END:variables
}
