package GymSystem;


import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Abhishek Mane
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        fetchComboBox(userIdBox);
    }
    
    public void fetchComboBox(JComboBox jb){
        try {
            Database db = new Database();
            String query = "select * from gymuser";
            ResultSet rs = db.stmt.executeQuery(query);
            
            while (rs.next()) {
               jb.addItem(rs.getString("user_id"));
            }
            
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        userIdBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setLocation(new java.awt.Point(700, 250));
        setMinimumSize(new java.awt.Dimension(750, 400));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Gym Management System");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 20, 480, 50);

        passwordField.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        getContentPane().add(passwordField);
        passwordField.setBounds(320, 190, 300, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("User ID -");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 130, 110, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Password -");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 196, 140, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton1.setText("Log In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 270, 220, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(409, 270, 210, 50);

        userIdBox.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(userIdBox);
        userIdBox.setBounds(320, 120, 300, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        passwordField.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
        Database db = new Database();
        
        String user = (String) userIdBox.getSelectedItem();
       
        String pass = passwordField.getText();
        
        String query = "select * from gymuser where user_id = '" + user + "' and password = '" + pass + "'";
        
        
        ResultSet rs = db.stmt.executeQuery(query);
        
        if(rs.next()){
            String privilage = rs.getString("privilage");
         
            System.out.println("Logged In Successfully");
            this.setVisible(false);
            //open new Frame
            new Dashboard(privilage).setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "Incorrect Password or User Id");
        }
        
        } catch (SQLException ex) {
            //Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Incorrect Password or User ID");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JComboBox<String> userIdBox;
    // End of variables declaration//GEN-END:variables
}
