/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GymSystem;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Abhishek Mane
 */
public class UpdateRecords extends javax.swing.JFrame {

    /**
     * Creates new form UpdateRecords
     */
    Dashboard dsb;
    public UpdateRecords() {
        super("Update Record");
        initComponents();
        fetchMembershipComboBox(msidCombo1);
        fetchFloorComboBox(flooridCombo1);
        fetchInstructorComboBox(insidCombo1);
        fetchInstructorComboBox(insidCombo);
        fetchPaymentComboBox(paymentidCombo1);
        fetchInventoryComboBox(itemidCombo1);
        fetchMemberComboBox(memidCombo1);
    }
    
    public UpdateRecords(Dashboard d){
        super("Update Record");
        dsb = d;
        initComponents();
        
        fetchMembershipComboBox(msidCombo1);
        fetchFloorComboBox(flooridCombo1);
        fetchInstructorComboBox(insidCombo1);
        fetchInstructorComboBox(insidCombo);
        fetchPaymentComboBox(paymentidCombo1);
        fetchInventoryComboBox(itemidCombo1);
        fetchMemberComboBox(memidCombo1);
    }
    
    public void fetchFloorComboBox(JComboBox jb){
        try {
            Database db = new Database();
            String query = "select * from floor";
            ResultSet rs = db.stmt.executeQuery(query);
            
            while (rs.next()) {
               jb.addItem(rs.getString("floor_id"));
            }
            
        } catch (Exception e) {
        }
    }
    
    public void fetchMemberComboBox(JComboBox jb){
        try {
            Database db = new Database();
            String query = "select * from member";
            ResultSet rs = db.stmt.executeQuery(query);
            
            while (rs.next()) {
              jb.addItem(rs.getString("member_id"));  
            }
            
        } catch (Exception e) {
        }
    }
    
    public void fetchMembershipComboBox(JComboBox jb){
        try {
            Database db = new Database();
            String query = "select * from membership";
            ResultSet rs = db.stmt.executeQuery(query);
            
            while (rs.next()) {
               jb.addItem(rs.getString("membership_id"));
            }
            
        } catch (Exception e) {
        }
    }
    
    public void fetchInstructorComboBox(JComboBox jb){
        try {
            Database db = new Database();
            String query = "select * from instructor";
            ResultSet rs = db.stmt.executeQuery(query);
            
            while (rs.next()) {
               jb.addItem(rs.getString("instructor_id"));
            }
            
        } catch (Exception e) {
        }
    }
    
    public void fetchPaymentComboBox(JComboBox jb){
        try {
            Database db = new Database();
            String query = "select * from payment";
            ResultSet rs = db.stmt.executeQuery(query);
            
            while (rs.next()) {
               jb.addItem(rs.getString("payment_id"));
            }
            
        } catch (Exception e) {
        }
    }
    
    public void fetchInventoryComboBox(JComboBox jb){
        try {
            Database db = new Database();
            String query = "select * from inventory";
            ResultSet rs = db.stmt.executeQuery(query);
            
            while (rs.next()) {
               jb.addItem(rs.getString("item_id"));
            }
            
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        insidCombo1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        memEmailField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        memNameField = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        memidCombo1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        msidCombo1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        tomField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        pomField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        insidCombo = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        instNameField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        instContactField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        instEmailField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        flooridCombo1 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        floorNameField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        paymentidCombo1 = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        paymentAmountField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        dateofPaymentField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        itemidCombo1 = new javax.swing.JComboBox<>();
        jButton7 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        itemQuantityField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 200));
        setMinimumSize(new java.awt.Dimension(1201, 650));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Update Records");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(470, 10, 300, 40);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 110, 50);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton8.setText("Refresh");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(1070, 0, 130, 50);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Select Member ID To Update Record Associated With It");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 40, 690, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Member Email - ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 330, 200, 30);

        insidCombo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(insidCombo1);
        insidCombo1.setBounds(220, 410, 240, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Update Member");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(720, 130, 230, 210);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("Instructor ID - ");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 420, 190, 30);

        memEmailField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(memEmailField);
        memEmailField.setBounds(220, 320, 240, 50);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Member Name - ");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 240, 200, 30);

        memNameField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(memNameField);
        memNameField.setBounds(220, 230, 240, 50);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Member ID - ");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 140, 170, 30);

        memidCombo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(memidCombo1);
        memidCombo1.setBounds(220, 130, 240, 50);

        jTabbedPane1.addTab("Members", jPanel1);

        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Select Membership ID To Update Record Associated With It");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 40, 720, 50);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Membership ID - ");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 200, 210, 30);

        msidCombo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(msidCombo1);
        msidCombo1.setBounds(290, 190, 240, 50);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("Update Membership");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(710, 130, 280, 210);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setText("Type of Membership - ");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(10, 280, 270, 30);

        tomField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(tomField);
        tomField.setBounds(290, 270, 240, 50);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel18.setText("Price of Membership - ");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(10, 360, 310, 30);

        pomField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel2.add(pomField);
        pomField.setBounds(290, 350, 240, 50);

        jTabbedPane1.addTab("Membership", jPanel2);

        jPanel3.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Select Instructor ID To Update Record Associated With It");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(10, 40, 690, 50);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("Instructor ID - ");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 200, 190, 30);

        insidCombo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(insidCombo);
        insidCombo.setBounds(260, 190, 250, 50);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("Update Instructor");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(723, 130, 247, 210);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel19.setText("Instructor Name -");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(10, 280, 220, 30);

        instNameField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(instNameField);
        instNameField.setBounds(260, 270, 250, 50);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setText("Instructor Contact -");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(10, 360, 250, 30);

        instContactField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(instContactField);
        instContactField.setBounds(260, 350, 250, 50);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setText("Instructor Email -");
        jPanel3.add(jLabel21);
        jLabel21.setBounds(10, 430, 220, 30);

        instEmailField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel3.add(instEmailField);
        instEmailField.setBounds(260, 420, 250, 50);

        jTabbedPane1.addTab("Instructor", jPanel3);

        jPanel4.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Select Floor ID To Update Record Associated With It");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(10, 40, 690, 50);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Floor ID - ");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(10, 200, 130, 30);

        flooridCombo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(flooridCombo1);
        flooridCombo1.setBounds(190, 190, 320, 50);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setText("Update Floor");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(730, 130, 220, 210);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setText("Floor Name -");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(10, 280, 170, 30);

        floorNameField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel4.add(floorNameField);
        floorNameField.setBounds(190, 270, 320, 50);

        jTabbedPane1.addTab("Floor", jPanel4);

        jPanel5.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Select Payment ID To Update Record Associated With It");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(10, 40, 690, 50);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Payment ID - ");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(10, 200, 170, 30);

        paymentidCombo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel5.add(paymentidCombo1);
        paymentidCombo1.setBounds(260, 190, 280, 50);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setText("Update Payment");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6);
        jButton6.setBounds(720, 130, 240, 210);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel23.setText("Payment Amount -");
        jPanel5.add(jLabel23);
        jLabel23.setBounds(10, 280, 230, 30);

        paymentAmountField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel5.add(paymentAmountField);
        paymentAmountField.setBounds(260, 270, 280, 50);

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel24.setText("Date of Payment -");
        jPanel5.add(jLabel24);
        jLabel24.setBounds(10, 360, 220, 30);

        dateofPaymentField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dateofPaymentField.setToolTipText("DD-MONTH-YY   Eg - 01-Jan-21");
        jPanel5.add(dateofPaymentField);
        dateofPaymentField.setBounds(260, 350, 280, 50);

        jTabbedPane1.addTab("Payment", jPanel5);

        jPanel6.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Select Item ID To Update Record Associated With It");
        jPanel6.add(jLabel7);
        jLabel7.setBounds(10, 40, 690, 50);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Item ID - ");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(10, 200, 170, 30);

        itemidCombo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel6.add(itemidCombo1);
        itemidCombo1.setBounds(220, 190, 290, 50);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setText("Update Inventory");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton7);
        jButton7.setBounds(730, 130, 250, 210);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel25.setText("Item Quantity -");
        jPanel6.add(jLabel25);
        jLabel25.setBounds(10, 280, 190, 30);

        itemQuantityField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel6.add(itemQuantityField);
        itemQuantityField.setBounds(220, 270, 290, 50);

        jTabbedPane1.addTab("Inventory", jPanel6);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 80, 1200, 520);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dsb.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new UpdateRecords(dsb).setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: update member
        if(memEmailField.getText().isEmpty() || memNameField.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "All Fields Are Mandatory"); 
        }else if( !memEmailField.getText().contains("@") ){
            JOptionPane.showMessageDialog(this,"Invalid Email ID");
        }else{
            
        try{
            Database db = new Database();
            String sql = "update member set name=?,email=?,instructor_id=? where member_id=?";
            PreparedStatement pst =  db.con.prepareStatement(sql);

            pst.setString(1, memNameField.getText());
            pst.setString(2, memEmailField.getText());
            pst.setString(3, (String) insidCombo1.getSelectedItem());
            pst.setString(4, (String) memidCombo1.getSelectedItem());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,"1 Row Affected \n Record Updated Successfully");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
      }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here: update membership
        if(tomField.getText().isEmpty() || pomField.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "All Fields Are Mandatory"); 
        }else if( pomField.getText().length() <= (int)0 || pomField.getText().length() >= (int)6 ){
            JOptionPane.showMessageDialog(this,"Price Must be greater than Zero \n&\n less than one Lakh");
        }else{
            
        try{
            Database db = new Database();
            String sql = "update membership set type_of_membership=?, price_of_membership=? where membership_id=?";
            PreparedStatement pst =  db.con.prepareStatement(sql);

            pst.setString(1, tomField.getText());
            pst.setInt(2, Integer.parseInt(pomField.getText()));
            pst.setString(3, (String) msidCombo1.getSelectedItem());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,"1 Row Affected \n Record Updated Successfully");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
        
      }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here: update instructor
        if(instContactField.getText().isEmpty() || instNameField.getText().isEmpty() || instEmailField.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "All Fields Are Mandatory"); 
        }else if( !instEmailField.getText().contains("@") || instContactField.getText().length() < 10 || instContactField.getText().length() > 10){
            JOptionPane.showMessageDialog(this,"Invalid Email \nOR\n Invalid Contact Number");
        }else{
     
        try{
            Database db = new Database();
            String sql = "update instructor set instructor_name=?, contact=?, email=? where instructor_id=?";
            PreparedStatement pst =  db.con.prepareStatement(sql);

            pst.setString(1, instNameField.getText());
            pst.setString(2, instContactField.getText());
            pst.setString(3, instEmailField.getText());
            pst.setString(4, (String) insidCombo.getSelectedItem());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,"1 Row Affected \n Record Updated Successfully");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
      }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:update floor
        if(floorNameField.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "All Fields Are Mandatory"); 
        }else{
            try{
                Database db = new Database();
                String sql = "update floor set floor_name=? where floor_id=?";
                PreparedStatement pst =  db.con.prepareStatement(sql);
            
                pst.setString(1, floorNameField.getText());
                pst.setString(2, (String) flooridCombo1.getSelectedItem());

                pst.executeUpdate();

                JOptionPane.showMessageDialog(this,"1 Row Affected \n Record Updated Successfully");
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
       }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here: update payment
        if(paymentAmountField.getText().isEmpty() || dateofPaymentField.getText().isEmpty()){
             JOptionPane.showMessageDialog(this, "All Fields Are Mandatory"); 
        }else if(paymentAmountField.getText().length() <= (int)0 || paymentAmountField.getText().length() >= (int)6 || Integer.parseInt(paymentAmountField.getText()) == 0){
            JOptionPane.showMessageDialog(this,"Price Must be greater than Zero \n&\n less than one Lakh");
        }else{
           
        try{
            Database db = new Database();
            String sql = "update payment set amount=?, date_of_payment=? where payment_id=?";
            PreparedStatement pst =  db.con.prepareStatement(sql);
            
            pst.setInt(1, Integer.parseInt(paymentAmountField.getText()) );
            pst.setString(2, dateofPaymentField.getText());
            pst.setString(3, (String) paymentidCombo1.getSelectedItem());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,"1 Row Affected \n Record Updated Successfully");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
     }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here: Update inventory
       if(itemQuantityField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "All Fields Are Mandatory"); 
       }else if( Integer.parseInt(itemQuantityField.getText()) == (int)0 ){
           JOptionPane.showMessageDialog(this,"Item Quantity Must be greater than Zero");
       }else{
        try{
            Database db = new Database();
            String sql = "update inventory set quantity=? where item_id=?";
            PreparedStatement pst =  db.con.prepareStatement(sql);
            
            pst.setInt(1, Integer.parseInt(itemQuantityField.getText()) );
            pst.setString(2, (String) itemidCombo1.getSelectedItem());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,"1 Row Affected \n Record Updated Successfully");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
     }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dateofPaymentField;
    private javax.swing.JTextField floorNameField;
    private javax.swing.JComboBox<String> flooridCombo1;
    private javax.swing.JComboBox<String> insidCombo;
    private javax.swing.JComboBox<String> insidCombo1;
    private javax.swing.JTextField instContactField;
    private javax.swing.JTextField instEmailField;
    private javax.swing.JTextField instNameField;
    private javax.swing.JTextField itemQuantityField;
    private javax.swing.JComboBox<String> itemidCombo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField memEmailField;
    private javax.swing.JTextField memNameField;
    private javax.swing.JComboBox<String> memidCombo1;
    private javax.swing.JComboBox<String> msidCombo1;
    private javax.swing.JTextField paymentAmountField;
    private javax.swing.JComboBox<String> paymentidCombo1;
    private javax.swing.JTextField pomField;
    private javax.swing.JTextField tomField;
    // End of variables declaration//GEN-END:variables
}
